<a href="https://colab.research.google.com/github/ojaspaul123/DL-journey/blob/main/ANN/Hyperparameter_Tuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
import pandas as pd
import numpy as np

In [60]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("uciml/pima-indians-diabetes-database")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'pima-indians-diabetes-database' dataset.
Path to dataset files: /kaggle/input/pima-indians-diabetes-database

In [61]:
from google.colab import files
uploaded = files.upload()
df = pd.read_csv('diabetes.csv')
df.head()

Saving diabetes.csv to diabetes (1).csv

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [62]:
df.shape

(768, 9)

In [63]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [64]:
X= df.iloc[:,:-1].values
y= df.iloc[:,-1].values

In [65]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [66]:
X.shape

(768, 8)

In [67]:
from sklearn.model_selection import train_test_split

In [68]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.2, random_state = 42)

In [69]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

**Basic Model**

In [70]:
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=8))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [71]:
model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['accuracy'])

In [72]:
model.fit(X_train, y_train, batch_size=32, epochs=100,validation_data=(X_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6433 - loss: 0.6406 - val_accuracy: 0.6753 - val_loss: 0.6087
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6987 - loss: 0.5748 - val_accuracy: 0.6753 - val_loss: 0.5693
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7182 - loss: 0.5352 - val_accuracy: 0.6948 - val_loss: 0.5428
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7313 - loss: 0.5108 - val_accuracy: 0.7208 - val_loss: 0.5226
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7427 - loss: 0.4937 - val_accuracy: 0.7338 - val_loss: 0.5122
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7573 - loss: 0.4809 - val_accuracy: 0.7597 - val_loss: 0.5050
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7671 - loss: 0.4704 - val_accuracy: 0.7597 - val_loss: 0.4999
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7785 - loss: 0.4621 - val_accuracy: 0.7727 - val_loss: 0.4963
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7720 - loss: 0.4553 - val_accuracy: 0.7727 - val_loss: 0.4932
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7850 - loss: 0.4488 - val_accuracy: 0.7468 - val_loss: 0.4913
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7883 - loss: 0.4439 - val_accuracy: 0.7597 - val_loss: 0.4931
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7850 - loss: 0.4416 - val_accuracy: 0.7662 - val_loss: 0.4954
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7915 - loss: 0.4392 - val_accuracy: 0.7403 - val_loss: 0.4933
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4337 - val_accuracy: 0.7597 - val_loss: 0.4960
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4324 - val_accuracy: 0.7403 - val_loss: 0.4970
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4289 - val_accuracy: 0.7403 - val_loss: 0.4978
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4269 - val_accuracy: 0.7403 - val_loss: 0.5021
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4252 - val_accuracy: 0.7403 - val_loss: 0.5049
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4225 - val_accuracy: 0.7468 - val_loss: 0.5071
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4217 - val_accuracy: 0.7403 - val_loss: 0.5120
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4190 - val_accuracy: 0.7468 - val_loss: 0.5090
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4181 - val_accuracy: 0.7532 - val_loss: 0.5147
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4155 - val_accuracy: 0.7403 - val_loss: 0.5122
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4147 - val_accuracy: 0.7468 - val_loss: 0.5137
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4124 - val_accuracy: 0.7403 - val_loss: 0.5204
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4126 - val_accuracy: 0.7532 - val_loss: 0.5215
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4140 - val_accuracy: 0.7338 - val_loss: 0.5166
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4079 - val_accuracy: 0.7532 - val_loss: 0.5177
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4087 - val_accuracy: 0.7532 - val_loss: 0.5185
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4073 - val_accuracy: 0.7403 - val_loss: 0.5181
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4046 - val_accuracy: 0.7403 - val_loss: 0.5208
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4039 - val_accuracy: 0.7403 - val_loss: 0.5235
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4023 - val_accuracy: 0.7468 - val_loss: 0.5274
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4005 - val_accuracy: 0.7403 - val_loss: 0.5292
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4005 - val_accuracy: 0.7338 - val_loss: 0.5291
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.3989 - val_accuracy: 0.7338 - val_loss: 0.5319
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.3974 - val_accuracy: 0.7338 - val_loss: 0.5317
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.3965 - val_accuracy: 0.7338 - val_loss: 0.5336
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.3954 - val_accuracy: 0.7403 - val_loss: 0.5335
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.3940 - val_accuracy: 0.7338 - val_loss: 0.5345
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.3937 - val_accuracy: 0.7403 - val_loss: 0.5364
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8094 - loss: 0.3926 - val_accuracy: 0.7403 - val_loss: 0.5352
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3934 - val_accuracy: 0.7338 - val_loss: 0.5371
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3898 - val_accuracy: 0.7468 - val_loss: 0.5323
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3901 - val_accuracy: 0.7468 - val_loss: 0.5325
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.3878 - val_accuracy: 0.7338 - val_loss: 0.5386
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.3890 - val_accuracy: 0.7338 - val_loss: 0.5385
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3873 - val_accuracy: 0.7403 - val_loss: 0.5372
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3857 - val_accuracy: 0.7338 - val_loss: 0.5396
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3844 - val_accuracy: 0.7403 - val_loss: 0.5393
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3837 - val_accuracy: 0.7273 - val_loss: 0.5413
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3831 - val_accuracy: 0.7468 - val_loss: 0.5425
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3820 - val_accuracy: 0.7403 - val_loss: 0.5449
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3804 - val_accuracy: 0.7403 - val_loss: 0.5474
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3796 - val_accuracy: 0.7403 - val_loss: 0.5497
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3803 - val_accuracy: 0.7597 - val_loss: 0.5468
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.3779 - val_accuracy: 0.7403 - val_loss: 0.5524
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8274 - loss: 0.3772 - val_accuracy: 0.7468 - val_loss: 0.5525
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3765 - val_accuracy: 0.7468 - val_loss: 0.5540
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3756 - val_accuracy: 0.7468 - val_loss: 0.5565
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3742 - val_accuracy: 0.7532 - val_loss: 0.5547
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.3733 - val_accuracy: 0.7403 - val_loss: 0.5594
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8322 - loss: 0.3723 - val_accuracy: 0.7403 - val_loss: 0.5603
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3729 - val_accuracy: 0.7468 - val_loss: 0.5627
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8388 - loss: 0.3713 - val_accuracy: 0.7403 - val_loss: 0.5624
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8404 - loss: 0.3711 - val_accuracy: 0.7532 - val_loss: 0.5642
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.3699 - val_accuracy: 0.7468 - val_loss: 0.5676
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3675 - val_accuracy: 0.7468 - val_loss: 0.5657
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8355 - loss: 0.3670 - val_accuracy: 0.7532 - val_loss: 0.5643
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3657 - val_accuracy: 0.7468 - val_loss: 0.5668
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3653 - val_accuracy: 0.7597 - val_loss: 0.5648
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3644 - val_accuracy: 0.7338 - val_loss: 0.5725
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3639 - val_accuracy: 0.7403 - val_loss: 0.5723
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3623 - val_accuracy: 0.7403 - val_loss: 0.5705
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3629 - val_accuracy: 0.7403 - val_loss: 0.5743
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8485 - loss: 0.3612 - val_accuracy: 0.7403 - val_loss: 0.5762
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3607 - val_accuracy: 0.7468 - val_loss: 0.5753
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3605 - val_accuracy: 0.7338 - val_loss: 0.5751
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3590 - val_accuracy: 0.7468 - val_loss: 0.5772
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8453 - loss: 0.3580 - val_accuracy: 0.7403 - val_loss: 0.5745
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8453 - loss: 0.3566 - val_accuracy: 0.7468 - val_loss: 0.5753
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8453 - loss: 0.3557 - val_accuracy: 0.7532 - val_loss: 0.5774
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8485 - loss: 0.3552 - val_accuracy: 0.7403 - val_loss: 0.5788
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3559 - val_accuracy: 0.7403 - val_loss: 0.5797
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8485 - loss: 0.3556 - val_accuracy: 0.7532 - val_loss: 0.5793
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8453 - loss: 0.3548 - val_accuracy: 0.7662 - val_loss: 0.5830
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8534 - loss: 0.3514 - val_accuracy: 0.7468 - val_loss: 0.5821
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8502 - loss: 0.3513 - val_accuracy: 0.7403 - val_loss: 0.5852
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8534 - loss: 0.3497 - val_accuracy: 0.7338 - val_loss: 0.5917
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8534 - loss: 0.3491 - val_accuracy: 0.7403 - val_loss: 0.5949
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8502 - loss: 0.3485 - val_accuracy: 0.7468 - val_loss: 0.5900
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8567 - loss: 0.3476 - val_accuracy: 0.7468 - val_loss: 0.5944
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8518 - loss: 0.3476 - val_accuracy: 0.7273 - val_loss: 0.5943
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8567 - loss: 0.3468 - val_accuracy: 0.7468 - val_loss: 0.5966
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8583 - loss: 0.3447 - val_accuracy: 0.7532 - val_loss: 0.5948
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3437 - val_accuracy: 0.7468 - val_loss: 0.5926
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8550 - loss: 0.3439 - val_accuracy: 0.7532 - val_loss: 0.5928
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8485 - loss: 0.3479 - val_accuracy: 0.7338 - val_loss: 0.5987
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8550 - loss: 0.3422 - val_accuracy: 0.7468 - val_loss: 0.5928
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8583 - loss: 0.3425 - val_accuracy: 0.7338 - val_loss: 0.6002

In [73]:
pip install -U keras-tuner

Requirement already satisfied: keras-tuner in /usr/local/lib/python3.12/dist-packages (1.4.8)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Requirement already satisfied: kt-legacy in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.0.5)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.81.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.1)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.5.20)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)

In [74]:
import kerastuner as kt

**Select Optimizer**

In [75]:
def build_model(hp):
  model=Sequential()
  model.add(Dense(32,activation='relu',input_dim=8))

  model.add(Dense(1,activation='sigmoid'))
  op = hp.Choice('optimizer',values=['adam','sgd','rmsprop','adadelta'])
  model.compile(optimizer=op,loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [76]:
tuner = kt.RandomSearch(build_model,objective='val_accuracy',max_trials=5)

Reloading Tuner from ./untitled_project/tuner0.json

In [77]:
tuner.search(X_train,y_train,epochs=10,validation_data=(X_test,y_test))

In [78]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [79]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [80]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [81]:
model.fit(X_train,y_train,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.7801 - loss: 0.4707 - val_accuracy: 0.7857 - val_loss: 0.5099
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4626 - val_accuracy: 0.7922 - val_loss: 0.5072
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4570 - val_accuracy: 0.7792 - val_loss: 0.5061
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4524 - val_accuracy: 0.7662 - val_loss: 0.5068
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4492 - val_accuracy: 0.7662 - val_loss: 0.5070
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4456 - val_accuracy: 0.7662 - val_loss: 0.5071
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4436 - val_accuracy: 0.7727 - val_loss: 0.5083
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7834 - loss: 0.4416 - val_accuracy: 0.7727 - val_loss: 0.5082
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7915 - loss: 0.4393 - val_accuracy: 0.7662 - val_loss: 0.5093
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - accuracy: 0.7850 - loss: 0.4381 - val_accuracy: 0.7662 - val_loss: 0.5096
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - accuracy: 0.7948 - loss: 0.4364 - val_accuracy: 0.7662 - val_loss: 0.5116
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.7899 - loss: 0.4348 - val_accuracy: 0.7662 - val_loss: 0.5110
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.7915 - loss: 0.4339 - val_accuracy: 0.7727 - val_loss: 0.5134
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7915 - loss: 0.4327 - val_accuracy: 0.7727 - val_loss: 0.5132
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.7899 - loss: 0.4315 - val_accuracy: 0.7727 - val_loss: 0.5139
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7932 - loss: 0.4309 - val_accuracy: 0.7727 - val_loss: 0.5159
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7915 - loss: 0.4300 - val_accuracy: 0.7727 - val_loss: 0.5172
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7948 - loss: 0.4291 - val_accuracy: 0.7727 - val_loss: 0.5174
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.7948 - loss: 0.4281 - val_accuracy: 0.7727 - val_loss: 0.5182
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7899 - loss: 0.4275 - val_accuracy: 0.7662 - val_loss: 0.5189
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7932 - loss: 0.4266 - val_accuracy: 0.7727 - val_loss: 0.5189
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7932 - loss: 0.4267 - val_accuracy: 0.7727 - val_loss: 0.5205
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7899 - loss: 0.4258 - val_accuracy: 0.7727 - val_loss: 0.5220
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7932 - loss: 0.4253 - val_accuracy: 0.7662 - val_loss: 0.5240
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.7866 - loss: 0.4248 - val_accuracy: 0.7662 - val_loss: 0.5246
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7932 - loss: 0.4240 - val_accuracy: 0.7662 - val_loss: 0.5250
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7915 - loss: 0.4234 - val_accuracy: 0.7662 - val_loss: 0.5275
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7932 - loss: 0.4234 - val_accuracy: 0.7662 - val_loss: 0.5282
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7866 - loss: 0.4225 - val_accuracy: 0.7597 - val_loss: 0.5294
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7883 - loss: 0.4221 - val_accuracy: 0.7597 - val_loss: 0.5295
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4213 - val_accuracy: 0.7597 - val_loss: 0.5297
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4210 - val_accuracy: 0.7597 - val_loss: 0.5309
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4206 - val_accuracy: 0.7597 - val_loss: 0.5320
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4201 - val_accuracy: 0.7662 - val_loss: 0.5328
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4195 - val_accuracy: 0.7532 - val_loss: 0.5328
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4193 - val_accuracy: 0.7597 - val_loss: 0.5332
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4189 - val_accuracy: 0.7597 - val_loss: 0.5327
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4182 - val_accuracy: 0.7532 - val_loss: 0.5347
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4179 - val_accuracy: 0.7532 - val_loss: 0.5358
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4177 - val_accuracy: 0.7532 - val_loss: 0.5362
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4179 - val_accuracy: 0.7532 - val_loss: 0.5356
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4169 - val_accuracy: 0.7532 - val_loss: 0.5375
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4159 - val_accuracy: 0.7532 - val_loss: 0.5379
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4161 - val_accuracy: 0.7597 - val_loss: 0.5376
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4157 - val_accuracy: 0.7597 - val_loss: 0.5369
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7948 - loss: 0.4154 - val_accuracy: 0.7597 - val_loss: 0.5373
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7899 - loss: 0.4151 - val_accuracy: 0.7597 - val_loss: 0.5381
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7915 - loss: 0.4146 - val_accuracy: 0.7597 - val_loss: 0.5379
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7899 - loss: 0.4145 - val_accuracy: 0.7597 - val_loss: 0.5396
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7899 - loss: 0.4139 - val_accuracy: 0.7597 - val_loss: 0.5403
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7899 - loss: 0.4138 - val_accuracy: 0.7597 - val_loss: 0.5387
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7883 - loss: 0.4130 - val_accuracy: 0.7597 - val_loss: 0.5401
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7915 - loss: 0.4126 - val_accuracy: 0.7597 - val_loss: 0.5400
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4123 - val_accuracy: 0.7597 - val_loss: 0.5399
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4122 - val_accuracy: 0.7597 - val_loss: 0.5393
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4117 - val_accuracy: 0.7597 - val_loss: 0.5401
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4116 - val_accuracy: 0.7662 - val_loss: 0.5403
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4111 - val_accuracy: 0.7597 - val_loss: 0.5411
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4108 - val_accuracy: 0.7597 - val_loss: 0.5407
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4105 - val_accuracy: 0.7597 - val_loss: 0.5419
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4097 - val_accuracy: 0.7597 - val_loss: 0.5430
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4099 - val_accuracy: 0.7597 - val_loss: 0.5444
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4093 - val_accuracy: 0.7597 - val_loss: 0.5436
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4090 - val_accuracy: 0.7597 - val_loss: 0.5446
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4089 - val_accuracy: 0.7597 - val_loss: 0.5446
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4084 - val_accuracy: 0.7597 - val_loss: 0.5446
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4085 - val_accuracy: 0.7597 - val_loss: 0.5449
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4079 - val_accuracy: 0.7532 - val_loss: 0.5458
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4076 - val_accuracy: 0.7532 - val_loss: 0.5451
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7932 - loss: 0.4071 - val_accuracy: 0.7532 - val_loss: 0.5459
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4072 - val_accuracy: 0.7532 - val_loss: 0.5447
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4066 - val_accuracy: 0.7532 - val_loss: 0.5449
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4064 - val_accuracy: 0.7532 - val_loss: 0.5454
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4061 - val_accuracy: 0.7532 - val_loss: 0.5458
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4061 - val_accuracy: 0.7532 - val_loss: 0.5463
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4057 - val_accuracy: 0.7468 - val_loss: 0.5473
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4050 - val_accuracy: 0.7532 - val_loss: 0.5480
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4045 - val_accuracy: 0.7532 - val_loss: 0.5490
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4046 - val_accuracy: 0.7597 - val_loss: 0.5501
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4045 - val_accuracy: 0.7532 - val_loss: 0.5510
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4046 - val_accuracy: 0.7468 - val_loss: 0.5501
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4033 - val_accuracy: 0.7597 - val_loss: 0.5478
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4033 - val_accuracy: 0.7597 - val_loss: 0.5491
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8029 - loss: 0.4030 - val_accuracy: 0.7532 - val_loss: 0.5500
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4028 - val_accuracy: 0.7532 - val_loss: 0.5510
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4027 - val_accuracy: 0.7468 - val_loss: 0.5511
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4023 - val_accuracy: 0.7468 - val_loss: 0.5517
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4020 - val_accuracy: 0.7532 - val_loss: 0.5502
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4017 - val_accuracy: 0.7532 - val_loss: 0.5514
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8029 - loss: 0.4012 - val_accuracy: 0.7468 - val_loss: 0.5514
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4012 - val_accuracy: 0.7468 - val_loss: 0.5523
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4010 - val_accuracy: 0.7468 - val_loss: 0.5532
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4003 - val_accuracy: 0.7532 - val_loss: 0.5541
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4003 - val_accuracy: 0.7403 - val_loss: 0.5549

**No. of Nodes in a layers**

In [82]:
def build_model(hp):
  model=Sequential()
  units = hp.Int('units',min_value=8,max_value=128,step=8)
  model.add(Dense(units=units,activation='relu',input_dim=8))

  model.add(Dense(1,activation='sigmoid'))
  op = hp.Choice('optimizer',values=['adam','sgd','rmsprop','adadelta'])
  model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [83]:
tuner = kt.RandomSearch(build_model,objective='val_accuracy',max_trials=5,directory='mydir')

Reloading Tuner from mydir/untitled_project/tuner0.json

In [84]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

In [85]:
tuner.get_best_hyperparameters()[0].values

{'units': 120, 'optimizer': 'sgd'}

In [86]:
model = tuner.get_best_models(num_models=1)[0]

In [87]:
model.fit(X_train,y_train,epochs=100,initial_epoch=6,validation_data=(X_test,y_test)  )

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.7622 - loss: 0.4594 - val_accuracy: 0.7727 - val_loss: 0.4971
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4504 - val_accuracy: 0.7403 - val_loss: 0.5002
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4465 - val_accuracy: 0.7468 - val_loss: 0.5024
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7785 - loss: 0.4437 - val_accuracy: 0.7597 - val_loss: 0.5011
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7736 - loss: 0.4412 - val_accuracy: 0.7597 - val_loss: 0.5017
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4379 - val_accuracy: 0.7662 - val_loss: 0.5017
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4361 - val_accuracy: 0.7662 - val_loss: 0.5038
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4338 - val_accuracy: 0.7662 - val_loss: 0.5056
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4319 - val_accuracy: 0.7532 - val_loss: 0.5109
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4306 - val_accuracy: 0.7597 - val_loss: 0.5112
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4290 - val_accuracy: 0.7532 - val_loss: 0.5151
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4277 - val_accuracy: 0.7597 - val_loss: 0.5139
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7801 - loss: 0.4259 - val_accuracy: 0.7597 - val_loss: 0.5151
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7801 - loss: 0.4242 - val_accuracy: 0.7532 - val_loss: 0.5192
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.7883 - loss: 0.4229 - val_accuracy: 0.7532 - val_loss: 0.5187
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.7899 - loss: 0.4219 - val_accuracy: 0.7662 - val_loss: 0.5171
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.7932 - loss: 0.4212 - val_accuracy: 0.7532 - val_loss: 0.5201
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7899 - loss: 0.4199 - val_accuracy: 0.7597 - val_loss: 0.5203
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7932 - loss: 0.4188 - val_accuracy: 0.7597 - val_loss: 0.5230
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7883 - loss: 0.4176 - val_accuracy: 0.7597 - val_loss: 0.5250
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.7883 - loss: 0.4171 - val_accuracy: 0.7662 - val_loss: 0.5246
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.7850 - loss: 0.4156 - val_accuracy: 0.7597 - val_loss: 0.5295
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7932 - loss: 0.4144 - val_accuracy: 0.7597 - val_loss: 0.5280
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7899 - loss: 0.4136 - val_accuracy: 0.7662 - val_loss: 0.5265
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7964 - loss: 0.4126 - val_accuracy: 0.7662 - val_loss: 0.5269
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7915 - loss: 0.4120 - val_accuracy: 0.7597 - val_loss: 0.5299
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7980 - loss: 0.4113 - val_accuracy: 0.7662 - val_loss: 0.5295
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7997 - loss: 0.4106 - val_accuracy: 0.7662 - val_loss: 0.5289
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7997 - loss: 0.4096 - val_accuracy: 0.7662 - val_loss: 0.5280
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.7948 - loss: 0.4084 - val_accuracy: 0.7662 - val_loss: 0.5325
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.8046 - loss: 0.4077 - val_accuracy: 0.7662 - val_loss: 0.5342
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8013 - loss: 0.4069 - val_accuracy: 0.7532 - val_loss: 0.5348
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8078 - loss: 0.4062 - val_accuracy: 0.7662 - val_loss: 0.5354
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.8094 - loss: 0.4056 - val_accuracy: 0.7662 - val_loss: 0.5333
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4044 - val_accuracy: 0.7662 - val_loss: 0.5347
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4050 - val_accuracy: 0.7597 - val_loss: 0.5333
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4034 - val_accuracy: 0.7597 - val_loss: 0.5336
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4030 - val_accuracy: 0.7597 - val_loss: 0.5380
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8078 - loss: 0.4019 - val_accuracy: 0.7597 - val_loss: 0.5363
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4016 - val_accuracy: 0.7597 - val_loss: 0.5360
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4008 - val_accuracy: 0.7597 - val_loss: 0.5365
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.3995 - val_accuracy: 0.7597 - val_loss: 0.5392
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.3997 - val_accuracy: 0.7532 - val_loss: 0.5375
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8078 - loss: 0.3995 - val_accuracy: 0.7532 - val_loss: 0.5377
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8127 - loss: 0.3987 - val_accuracy: 0.7532 - val_loss: 0.5377
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8046 - loss: 0.3968 - val_accuracy: 0.7468 - val_loss: 0.5397
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8127 - loss: 0.3969 - val_accuracy: 0.7597 - val_loss: 0.5387
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8094 - loss: 0.3960 - val_accuracy: 0.7532 - val_loss: 0.5411
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8111 - loss: 0.3962 - val_accuracy: 0.7403 - val_loss: 0.5399
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8094 - loss: 0.3952 - val_accuracy: 0.7468 - val_loss: 0.5439
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8046 - loss: 0.3954 - val_accuracy: 0.7468 - val_loss: 0.5448
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8111 - loss: 0.3945 - val_accuracy: 0.7403 - val_loss: 0.5413
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8176 - loss: 0.3931 - val_accuracy: 0.7403 - val_loss: 0.5429
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8176 - loss: 0.3932 - val_accuracy: 0.7338 - val_loss: 0.5439
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8078 - loss: 0.3921 - val_accuracy: 0.7403 - val_loss: 0.5437
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3916 - val_accuracy: 0.7338 - val_loss: 0.5451
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.3915 - val_accuracy: 0.7403 - val_loss: 0.5441
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3905 - val_accuracy: 0.7403 - val_loss: 0.5452
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3902 - val_accuracy: 0.7338 - val_loss: 0.5443
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3903 - val_accuracy: 0.7338 - val_loss: 0.5497
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3891 - val_accuracy: 0.7338 - val_loss: 0.5506
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8160 - loss: 0.3884 - val_accuracy: 0.7403 - val_loss: 0.5519
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.3866 - val_accuracy: 0.7403 - val_loss: 0.5491
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3880 - val_accuracy: 0.7403 - val_loss: 0.5571
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3865 - val_accuracy: 0.7338 - val_loss: 0.5543
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.3868 - val_accuracy: 0.7403 - val_loss: 0.5556
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3861 - val_accuracy: 0.7403 - val_loss: 0.5554
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3844 - val_accuracy: 0.7403 - val_loss: 0.5536
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3841 - val_accuracy: 0.7403 - val_loss: 0.5573
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3843 - val_accuracy: 0.7468 - val_loss: 0.5518
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3839 - val_accuracy: 0.7208 - val_loss: 0.5549
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3832 - val_accuracy: 0.7273 - val_loss: 0.5566
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3836 - val_accuracy: 0.7403 - val_loss: 0.5584
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3824 - val_accuracy: 0.7273 - val_loss: 0.5603
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3821 - val_accuracy: 0.7208 - val_loss: 0.5618
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3810 - val_accuracy: 0.7403 - val_loss: 0.5557
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3812 - val_accuracy: 0.7338 - val_loss: 0.5577
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3810 - val_accuracy: 0.7338 - val_loss: 0.5588
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3798 - val_accuracy: 0.7273 - val_loss: 0.5597
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3798 - val_accuracy: 0.7338 - val_loss: 0.5619
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8274 - loss: 0.3787 - val_accuracy: 0.7338 - val_loss: 0.5632
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8290 - loss: 0.3791 - val_accuracy: 0.7338 - val_loss: 0.5636
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8274 - loss: 0.3780 - val_accuracy: 0.7403 - val_loss: 0.5618
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8241 - loss: 0.3772 - val_accuracy: 0.7403 - val_loss: 0.5617
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3768 - val_accuracy: 0.7403 - val_loss: 0.5633
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8306 - loss: 0.3767 - val_accuracy: 0.7403 - val_loss: 0.5611
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3766 - val_accuracy: 0.7403 - val_loss: 0.5636
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8322 - loss: 0.3760 - val_accuracy: 0.7532 - val_loss: 0.5629
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3763 - val_accuracy: 0.7338 - val_loss: 0.5621
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3745 - val_accuracy: 0.7468 - val_loss: 0.5619
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3747 - val_accuracy: 0.7208 - val_loss: 0.5679
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3747 - val_accuracy: 0.7403 - val_loss: 0.5663
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3730 - val_accuracy: 0.7338 - val_loss: 0.5669
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3736 - val_accuracy: 0.7403 - val_loss: 0.5677

**How to select no. of layers**

In [88]:
def build_modell(hp):
  model = Sequential()

  model.add(Dense(72,activation='relu',input_dim=8))

  for i in range(hp.Int('num_layers',min_value=1,max_value=10)):
    model.add(Dense(72,activation='relu'))

  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [89]:
tuner_1 = kt.RandomSearch(
    build_modell,
    objective='val_accuracy',
    max_trials=5,
    directory='mydir',
    project_name='num_layers_search'
)

Reloading Tuner from mydir/num_layers_search/tuner0.json

In [90]:
tuner_1.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

In [91]:
tuner_1.get_best_hyperparameters()[0].values

{'num_layers': 6}

In [92]:
model = tuner_1.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 18 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [93]:
model.fit(X_train,y_train,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - accuracy: 0.7590 - loss: 0.4827 - val_accuracy: 0.7078 - val_loss: 0.5275
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4518 - val_accuracy: 0.7143 - val_loss: 0.5542
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7964 - loss: 0.4318 - val_accuracy: 0.7532 - val_loss: 0.5690
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4270 - val_accuracy: 0.7597 - val_loss: 0.5491
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4114 - val_accuracy: 0.7208 - val_loss: 0.5485
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4166 - val_accuracy: 0.7532 - val_loss: 0.5520
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3946 - val_accuracy: 0.7532 - val_loss: 0.5498
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3925 - val_accuracy: 0.7532 - val_loss: 0.5962
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8290 - loss: 0.3824 - val_accuracy: 0.7143 - val_loss: 0.5775
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8420 - loss: 0.3666 - val_accuracy: 0.7013 - val_loss: 0.6726
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8371 - loss: 0.3665 - val_accuracy: 0.6623 - val_loss: 0.6272
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8388 - loss: 0.3542 - val_accuracy: 0.7403 - val_loss: 0.6320
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8322 - loss: 0.3639 - val_accuracy: 0.7403 - val_loss: 0.6417
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8648 - loss: 0.3325 - val_accuracy: 0.6558 - val_loss: 0.6847
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8599 - loss: 0.3240 - val_accuracy: 0.7273 - val_loss: 0.6454
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8795 - loss: 0.2983 - val_accuracy: 0.6623 - val_loss: 0.8687
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8632 - loss: 0.3184 - val_accuracy: 0.7273 - val_loss: 0.7387
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8795 - loss: 0.3105 - val_accuracy: 0.7143 - val_loss: 0.7069
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8893 - loss: 0.2834 - val_accuracy: 0.7273 - val_loss: 0.7450
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8958 - loss: 0.2766 - val_accuracy: 0.7403 - val_loss: 0.7926
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8974 - loss: 0.2675 - val_accuracy: 0.6688 - val_loss: 0.8557
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8844 - loss: 0.2830 - val_accuracy: 0.6753 - val_loss: 0.8743
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8974 - loss: 0.2636 - val_accuracy: 0.6883 - val_loss: 0.7892
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8974 - loss: 0.2551 - val_accuracy: 0.7143 - val_loss: 0.9153
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8941 - loss: 0.2467 - val_accuracy: 0.7338 - val_loss: 0.9107
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9088 - loss: 0.2245 - val_accuracy: 0.7338 - val_loss: 0.8834
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9218 - loss: 0.2182 - val_accuracy: 0.6623 - val_loss: 1.1937
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9218 - loss: 0.2082 - val_accuracy: 0.7078 - val_loss: 0.9547
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9104 - loss: 0.2083 - val_accuracy: 0.6234 - val_loss: 1.1490
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9283 - loss: 0.1908 - val_accuracy: 0.6234 - val_loss: 1.0336
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9251 - loss: 0.1971 - val_accuracy: 0.6753 - val_loss: 1.1308
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9169 - loss: 0.1949 - val_accuracy: 0.6818 - val_loss: 1.1022
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9414 - loss: 0.1532 - val_accuracy: 0.7273 - val_loss: 1.3129
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9463 - loss: 0.1646 - val_accuracy: 0.6948 - val_loss: 1.1593
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9283 - loss: 0.1754 - val_accuracy: 0.6104 - val_loss: 1.4146
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9609 - loss: 0.1211 - val_accuracy: 0.7078 - val_loss: 1.3546
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9300 - loss: 0.1733 - val_accuracy: 0.6883 - val_loss: 1.2989
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9528 - loss: 0.1257 - val_accuracy: 0.6753 - val_loss: 1.3568
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9479 - loss: 0.1364 - val_accuracy: 0.6883 - val_loss: 1.4544
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9674 - loss: 0.1029 - val_accuracy: 0.6688 - val_loss: 1.5833
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9511 - loss: 0.1352 - val_accuracy: 0.6494 - val_loss: 1.7027
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9544 - loss: 0.1350 - val_accuracy: 0.6818 - val_loss: 1.3319
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9674 - loss: 0.0824 - val_accuracy: 0.6688 - val_loss: 1.5845
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9430 - loss: 0.1651 - val_accuracy: 0.6818 - val_loss: 1.6832
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9625 - loss: 0.0923 - val_accuracy: 0.7013 - val_loss: 1.7918
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9674 - loss: 0.0875 - val_accuracy: 0.6948 - val_loss: 1.6604
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9772 - loss: 0.0782 - val_accuracy: 0.6818 - val_loss: 1.8306
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9674 - loss: 0.0933 - val_accuracy: 0.6558 - val_loss: 2.1188
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9707 - loss: 0.0765 - val_accuracy: 0.6299 - val_loss: 2.2157
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9658 - loss: 0.0802 - val_accuracy: 0.7338 - val_loss: 2.0563
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9691 - loss: 0.0960 - val_accuracy: 0.6558 - val_loss: 1.8323
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9805 - loss: 0.0662 - val_accuracy: 0.7078 - val_loss: 1.9195
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9739 - loss: 0.0851 - val_accuracy: 0.6818 - val_loss: 1.9670
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9707 - loss: 0.0829 - val_accuracy: 0.6948 - val_loss: 2.0645
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9870 - loss: 0.0393 - val_accuracy: 0.7208 - val_loss: 2.2401
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9772 - loss: 0.0599 - val_accuracy: 0.6948 - val_loss: 2.0299
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9528 - loss: 0.1379 - val_accuracy: 0.6818 - val_loss: 1.9580
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9935 - loss: 0.0226 - val_accuracy: 0.6948 - val_loss: 2.2457
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9788 - loss: 0.0644 - val_accuracy: 0.7013 - val_loss: 2.1339
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9739 - loss: 0.0807 - val_accuracy: 0.7208 - val_loss: 2.0256
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0212 - val_accuracy: 0.6753 - val_loss: 2.1978
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9805 - loss: 0.0867 - val_accuracy: 0.7143 - val_loss: 2.4708
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9967 - loss: 0.0130 - val_accuracy: 0.6494 - val_loss: 2.8992
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9707 - loss: 0.0701 - val_accuracy: 0.7013 - val_loss: 2.5633
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9902 - loss: 0.0261 - val_accuracy: 0.6688 - val_loss: 2.7500
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9707 - loss: 0.1096 - val_accuracy: 0.6753 - val_loss: 2.2196
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0157 - val_accuracy: 0.6688 - val_loss: 2.4838
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0170 - val_accuracy: 0.7013 - val_loss: 2.9604
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9853 - loss: 0.0526 - val_accuracy: 0.7013 - val_loss: 2.6775
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9788 - loss: 0.0751 - val_accuracy: 0.6883 - val_loss: 2.4669
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0093 - val_accuracy: 0.6883 - val_loss: 2.5496
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9707 - loss: 0.0859 - val_accuracy: 0.6883 - val_loss: 2.5259
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0160 - val_accuracy: 0.7013 - val_loss: 2.8958
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9805 - loss: 0.0586 - val_accuracy: 0.6623 - val_loss: 2.5807
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9886 - loss: 0.0391 - val_accuracy: 0.6818 - val_loss: 2.5313
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9853 - loss: 0.0374 - val_accuracy: 0.6753 - val_loss: 2.8340
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0300 - val_accuracy: 0.6883 - val_loss: 2.3666
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9902 - loss: 0.0231 - val_accuracy: 0.6883 - val_loss: 2.6644
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9870 - loss: 0.0425 - val_accuracy: 0.6753 - val_loss: 2.5274
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0128 - val_accuracy: 0.7013 - val_loss: 2.9557
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9821 - loss: 0.0642 - val_accuracy: 0.6883 - val_loss: 2.6334
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9870 - loss: 0.0411 - val_accuracy: 0.6753 - val_loss: 2.7509
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9951 - loss: 0.0135 - val_accuracy: 0.6818 - val_loss: 2.9006
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9886 - loss: 0.0369 - val_accuracy: 0.6948 - val_loss: 2.9124
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9951 - loss: 0.0121 - val_accuracy: 0.7143 - val_loss: 2.9683
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9788 - loss: 0.0929 - val_accuracy: 0.6688 - val_loss: 3.2149
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9919 - loss: 0.0177 - val_accuracy: 0.6883 - val_loss: 2.6396
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9886 - loss: 0.0508 - val_accuracy: 0.6623 - val_loss: 2.7871
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9984 - loss: 0.0036 - val_accuracy: 0.6753 - val_loss: 3.0175
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9870 - loss: 0.0476 - val_accuracy: 0.6364 - val_loss: 3.1085
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9886 - loss: 0.0245 - val_accuracy: 0.7078 - val_loss: 2.8906
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0148 - val_accuracy: 0.6688 - val_loss: 3.1468
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0112 - val_accuracy: 0.6948 - val_loss: 3.4711
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0148 - val_accuracy: 0.6883 - val_loss: 3.3423

In [101]:
def build_model(hp):
  model = Sequential()

  counter =0

  for i in range (hp.Int('num_layers',min_value=1,max_value=10)):
    if counter ==0:
      model.add(Dense(hp.Int('units'+str(i),min_value=8,max_value=128,step=8),
                      activation=hp.Choice('activation'+str(i),values=['relu','tanh','sigmoid']),
                      input_dim =8))
    else:
        model.add(Dense(hp.Int('units'+str(i),min_value=8,max_value=128,step=8),
                      activation=hp.Choice('activation'+str(i),values=['relu','tanh','sigmoid'])
              ))

        counter +=1


  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer=hp.Choice('optimizer',values=['adam','sgd','rmsprop','adadelta']),
                loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [102]:
tuner = kt.RandomSearch(build_model,objective='val_accuracy',max_trials=3,directory='mydir',project_name="final")

Reloading Tuner from mydir/final/tuner0.json

In [103]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

In [104]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 7,
 'units0': 24,
 'activation0': 'relu',
 'optimizer': 'rmsprop',
 'units1': 8,
 'activation1': 'relu',
 'units2': 8,
 'activation2': 'relu',
 'units3': 8,
 'activation3': 'relu',
 'units4': 8,
 'activation4': 'relu',
 'units5': 8,
 'activation5': 'relu',
 'units6': 8,
 'activation6': 'relu'}

In [105]:
model = tuner.get_best_models(num_models=1)[0]

In [106]:
model.fit(X_train,y_train,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 0.7410 - loss: 0.5556 - val_accuracy: 0.7662 - val_loss: 0.5377
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7524 - loss: 0.5214 - val_accuracy: 0.7468 - val_loss: 0.5209
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7606 - loss: 0.5017 - val_accuracy: 0.7597 - val_loss: 0.5107
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4876 - val_accuracy: 0.7597 - val_loss: 0.5031
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4793 - val_accuracy: 0.7597 - val_loss: 0.5003
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4714 - val_accuracy: 0.7532 - val_loss: 0.5022
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4668 - val_accuracy: 0.7727 - val_loss: 0.4982
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4616 - val_accuracy: 0.7727 - val_loss: 0.4989
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4566 - val_accuracy: 0.7468 - val_loss: 0.5035
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4549 - val_accuracy: 0.7403 - val_loss: 0.5091
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4547 - val_accuracy: 0.7532 - val_loss: 0.5016
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4480 - val_accuracy: 0.7727 - val_loss: 0.5071
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4473 - val_accuracy: 0.7727 - val_loss: 0.5013
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4471 - val_accuracy: 0.7792 - val_loss: 0.5066
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4411 - val_accuracy: 0.7857 - val_loss: 0.5110
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4413 - val_accuracy: 0.7857 - val_loss: 0.5055
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4380 - val_accuracy: 0.7403 - val_loss: 0.5148
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4376 - val_accuracy: 0.7662 - val_loss: 0.5075
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4325 - val_accuracy: 0.7468 - val_loss: 0.5140
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4319 - val_accuracy: 0.7857 - val_loss: 0.5120
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4295 - val_accuracy: 0.7792 - val_loss: 0.5059
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4282 - val_accuracy: 0.7792 - val_loss: 0.5130
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4291 - val_accuracy: 0.7662 - val_loss: 0.5139
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8094 - loss: 0.4267 - val_accuracy: 0.7727 - val_loss: 0.5181
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4227 - val_accuracy: 0.7792 - val_loss: 0.5151
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4208 - val_accuracy: 0.7662 - val_loss: 0.5114
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4235 - val_accuracy: 0.7662 - val_loss: 0.5148
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8143 - loss: 0.4194 - val_accuracy: 0.7727 - val_loss: 0.5148
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4155 - val_accuracy: 0.7597 - val_loss: 0.5290
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4158 - val_accuracy: 0.7468 - val_loss: 0.5383
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8111 - loss: 0.4141 - val_accuracy: 0.7468 - val_loss: 0.5236
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8143 - loss: 0.4112 - val_accuracy: 0.7532 - val_loss: 0.5309
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8013 - loss: 0.4111 - val_accuracy: 0.7727 - val_loss: 0.5383
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8208 - loss: 0.4103 - val_accuracy: 0.7597 - val_loss: 0.5383
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8143 - loss: 0.4070 - val_accuracy: 0.7273 - val_loss: 0.5538
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8143 - loss: 0.4057 - val_accuracy: 0.7727 - val_loss: 0.5282
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8192 - loss: 0.4008 - val_accuracy: 0.7468 - val_loss: 0.5411
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8143 - loss: 0.4022 - val_accuracy: 0.7597 - val_loss: 0.5446
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8274 - loss: 0.4001 - val_accuracy: 0.7597 - val_loss: 0.5529
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8160 - loss: 0.3994 - val_accuracy: 0.7597 - val_loss: 0.5561
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8160 - loss: 0.3969 - val_accuracy: 0.7727 - val_loss: 0.5568
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3977 - val_accuracy: 0.7662 - val_loss: 0.5558
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3944 - val_accuracy: 0.7727 - val_loss: 0.5512
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3929 - val_accuracy: 0.7727 - val_loss: 0.5527
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8241 - loss: 0.3879 - val_accuracy: 0.7468 - val_loss: 0.5716
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3901 - val_accuracy: 0.7597 - val_loss: 0.5662
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3881 - val_accuracy: 0.7597 - val_loss: 0.5625
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3844 - val_accuracy: 0.7662 - val_loss: 0.5637
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3845 - val_accuracy: 0.7597 - val_loss: 0.5717
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3801 - val_accuracy: 0.7662 - val_loss: 0.5808
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3822 - val_accuracy: 0.7662 - val_loss: 0.5733
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8322 - loss: 0.3780 - val_accuracy: 0.7727 - val_loss: 0.5839
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3752 - val_accuracy: 0.7468 - val_loss: 0.5811
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3760 - val_accuracy: 0.7662 - val_loss: 0.5891
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3692 - val_accuracy: 0.7662 - val_loss: 0.5953
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3727 - val_accuracy: 0.7468 - val_loss: 0.5926
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3680 - val_accuracy: 0.7727 - val_loss: 0.5967
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3685 - val_accuracy: 0.7662 - val_loss: 0.5949
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8420 - loss: 0.3651 - val_accuracy: 0.7662 - val_loss: 0.5901
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3630 - val_accuracy: 0.7532 - val_loss: 0.6051
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3644 - val_accuracy: 0.7468 - val_loss: 0.6032
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3596 - val_accuracy: 0.7597 - val_loss: 0.6108
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8436 - loss: 0.3604 - val_accuracy: 0.7468 - val_loss: 0.6148
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3584 - val_accuracy: 0.7403 - val_loss: 0.6200
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8371 - loss: 0.3575 - val_accuracy: 0.7597 - val_loss: 0.6130
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8485 - loss: 0.3502 - val_accuracy: 0.7597 - val_loss: 0.6186
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3518 - val_accuracy: 0.7597 - val_loss: 0.6282
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8453 - loss: 0.3545 - val_accuracy: 0.7403 - val_loss: 0.6349
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.3491 - val_accuracy: 0.7403 - val_loss: 0.6355
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8550 - loss: 0.3490 - val_accuracy: 0.7597 - val_loss: 0.6189
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3464 - val_accuracy: 0.7338 - val_loss: 0.6401
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3467 - val_accuracy: 0.7727 - val_loss: 0.6313
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8583 - loss: 0.3428 - val_accuracy: 0.7662 - val_loss: 0.6264
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8534 - loss: 0.3415 - val_accuracy: 0.7727 - val_loss: 0.6325
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8599 - loss: 0.3385 - val_accuracy: 0.7468 - val_loss: 0.6553
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8648 - loss: 0.3325 - val_accuracy: 0.7208 - val_loss: 0.6795
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8534 - loss: 0.3387 - val_accuracy: 0.7532 - val_loss: 0.6557
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8599 - loss: 0.3369 - val_accuracy: 0.7532 - val_loss: 0.6633
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3340 - val_accuracy: 0.7727 - val_loss: 0.6564
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.3336 - val_accuracy: 0.7273 - val_loss: 0.6784
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8713 - loss: 0.3328 - val_accuracy: 0.7273 - val_loss: 0.6685
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8616 - loss: 0.3309 - val_accuracy: 0.7532 - val_loss: 0.6694
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8583 - loss: 0.3285 - val_accuracy: 0.7662 - val_loss: 0.6634
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8567 - loss: 0.3291 - val_accuracy: 0.7532 - val_loss: 0.6688
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8697 - loss: 0.3255 - val_accuracy: 0.7468 - val_loss: 0.6759
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8599 - loss: 0.3258 - val_accuracy: 0.7403 - val_loss: 0.6804
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8632 - loss: 0.3211 - val_accuracy: 0.7403 - val_loss: 0.6801
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8648 - loss: 0.3229 - val_accuracy: 0.7338 - val_loss: 0.6739
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8664 - loss: 0.3197 - val_accuracy: 0.7338 - val_loss: 0.6780
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8697 - loss: 0.3191 - val_accuracy: 0.7532 - val_loss: 0.6678
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8779 - loss: 0.3134 - val_accuracy: 0.7403 - val_loss: 0.6892
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8632 - loss: 0.3161 - val_accuracy: 0.7273 - val_loss: 0.6765
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8681 - loss: 0.3148 - val_accuracy: 0.7532 - val_loss: 0.6853
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8746 - loss: 0.3081 - val_accuracy: 0.7273 - val_loss: 0.7234